runtime: nodejs18

env_variables:
  # Database Google Cloud SQL
  DB_HOST: "34.45.56.79"
  DB_PORT: "3306"
  DB_NAME: "sala_livre"
  DB_USER: "app_user"
  DB_PASSWORD: "Neves@2025"
  
  # Secrets de produção
  JWT_SECRET: "sala_livre_jwt_secret_production_2025_super_secure"
  SESSION_SECRET: "sala_livre_session_secret_production_2025_ultra_secure"
  
  # Configurações da aplicação
  NODE_ENV: "production"
  APP_NAME: "Sala Livre"
  APP_URL: "https://sala-livre-api.appspot.com"
  
  # CORS para Netlify
  CORS_ORIGIN: "https://sala-livre-app.netlify.app"
  
  # Google OAuth (configure se usar)
  # GOOGLE_CLIENT_ID: "seu_client_id.apps.googleusercontent.com"
  # GOOGLE_CLIENT_SECRET: "seu_client_secret"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
