# Netlify Build Configuration

[build]
  # Diretório com os arquivos do frontend
  publish = "netlify"
  
  # Diretório das functions
  functions = "netlify/functions"
  
  # Comando de build (não necessário para frontend estático)
  command = "echo 'Frontend estático pronto para deploy'"

[build.environment]
  # Variáveis de ambiente para o frontend
  NODE_VERSION = "18"

# Redirecionamentos e regras
[[redirects]]
  # Login function (simples)
  from = "/login"
  to = "/.netlify/functions/login-simple"
  status = 200

[[redirects]]
  # Register function
  from = "/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  # Test function
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  # Legacy API routes
  from = "/api/auth/login"
  to = "/.netlify/functions/login-simple"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/.netlify/functions/login"
  to = "/.netlify/functions/login-simple"
  status = 200

[[redirects]]
  # SPA fallback - todas as rotas vão para index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers para assets estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
