# Netlify Build Configuration

[build]
  # Diretório com os arquivos do frontend
  publish = "netlify"
  
  # Diretório das functions
  functions = "netlify/functions"
  
  # Comando de build (não necessário para frontend estático)
  command = "echo 'Frontend estático pronto para deploy'"

[build.environment]
  # Variáveis de ambiente para o frontend
  NODE_VERSION = "18"

# Redirecionamentos e regras para API com Google Cloud SQL
[[redirects]]
  # Health Check
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  # Usuários API
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  # Usuário específico
  from = "/api/users/*"
  to = "/.netlify/functions/users?id=:splat"
  status = 200

[[redirects]]
  # Reuniões API
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  # Reunião específica
  from = "/api/bookings/*"
  to = "/.netlify/functions/bookings?id=:splat"
  status = 200

[[redirects]]
  # Salas API
  from = "/api/rooms"
  to = "/.netlify/functions/rooms"
  status = 200

[[redirects]]
  # Sala específica
  from = "/api/rooms/*"
  to = "/.netlify/functions/rooms?id=:splat"
  status = 200

# Funções de autenticação (mantidas para compatibilidade)
[[redirects]]
  # Login function (simples)
  from = "/login"
  to = "/.netlify/functions/login-simple"
  status = 200

[[redirects]]
  # Register function
  from = "/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  # Legacy API routes
  from = "/api/auth/login"
  to = "/.netlify/functions/login-simple"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  # SPA fallback - todas as rotas vão para index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers para assets estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
